---
- hosts: all
  become: true
  tasks:
   - name: install java
     become: yes
     apt:
       name: openjdk-8-jdk
       state: present
   - name: install maven
     apt:
       name: maven
       state: present
       update_cache: yes
     notify:
     - run update
   - name: install nginx
     apt:
       name: nginx
       state: latest
   - name: install docker
     apt:
       pkg: docker.io
       state: present
   - name: start docker service
     service:
        name: docker
        state: started
        enabled: true
   - name: deploy war-test image
     command: sudo docker rm $(sudo docker ps -a -q) -f
   - name: deploy war-test image2  
     command: sudo docker rmi $(sudo docker images -q)
   - name: deploy war-test image3  
     command: sudo docker run -it -d -p 8087:8080 pitchunath/war-test:1.0.0
